module sim_msgs {
    struct ImageData_ {
        uint32 res_x;
        uint32 res_y;

        float depth_min;
        float depth_max;

        sequence<uint8> rgb_data;
        sequence<float> depth_data;
    };
};