#pragma once

#define FRAME_WIDTH 640
#define FRAME_HEIGHT 480
#define FRAME_BUFFER_ELEMENTS_RGB FRAME_WIDTH * FRAME_HEIGHT * 3
#define FRAME_BUFFER_ELEMENTS_DEPTH FRAME_WIDTH * FRAME_HEIGHT 

#define IOX_TOPIC_SIM_CAMERA_DEPTH "rt/sim/depth"
#define IOX_TOPIC_SIM_CAMERA_RGB "rt/sim/rgb"

#define IOX_MAX_PUBLISHERS 1
#define IOX_MAX_SUBSCRIBERS 1
#define IOX_SUBSCRIBER_MAX_BUFFER_SIZE 3 // we really only care about the most recent frames
#define IOX_SUBSCRIBER_MAX_BORROWED_SAMPLES 2
#define IOX_HISTORY_SIZE 1