#pragma once

#define FRAME_WIDTH 640
#define FRAME_HEIGHT 480
#define FRAME_BUFFER_ELEMENTS_RGB FRAME_WIDTH * FRAME_HEIGHT * 3
#define FRAME_BUFFER_ELEMENTS_DEPTH FRAME_WIDTH * FRAME_HEIGHT 

#define DDS_TOPIC_SIM_CAMERA_DEPTH "rt/sim/depth"
#define DDS_TOPIC_SIM_CAMERA_RGB "rt/sim/rgb"