#pragma once

#define FRAME_WIDTH 640
#define FRAME_HEIGHT 480
#define FRAME_BUFFER_ELEMENTS_RGB FRAME_WIDTH * FRAME_HEIGHT * 3
#define FRAME_BUFFER_ELEMENTS_DEPTH FRAME_WIDTH * FRAME_HEIGHT 

#define DDS_TOPIC_SIM_CAMERA_DEPTH "rt/sim/depth"
#define DDS_TOPIC_SIM_CAMERA_RGB "rt/sim/rgb"

#define IOX2_MAX_PUBLISHERS 1
#define IOX2_MAX_SUBSCRIBERS 4
#define IOX2_SUBSCRIBER_MAX_BUFFER_SIZE 2
#define IOX2_SUBSCRIBER_MAX_BORROWED_SAMPLES 1
#define IOX2_HISTORY_SIZE 1