FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FRAME_BUFFER_ELEMENTS_RGB = FRAME_WIDTH * FRAME_HEIGHT * 3
FRAME_BUFFER_ELEMENTS_DEPTH = FRAME_WIDTH * FRAME_HEIGHT 

DDS_TOPIC_SIM_CAMERA_DEPTH = "rt/sim/depth"
DDS_TOPIC_SIM_CAMERA_RGB = "rt/sim/rgb"


IOX2_MAX_PUBLISHERS = 1
IOX2_MAX_SUBSCRIBERS = 1
IOX2_SUBSCRIBER_MAX_BUFFER_SIZE = 3 # we really only care about the most recent frames
IOX2_SUBSCRIBER_MAX_BORROWED_SAMPLES = 2
IOX2_HISTORY_SIZE = 1