FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FRAME_BUFFER_ELEMENTS_RGB = FRAME_WIDTH * FRAME_HEIGHT * 3
FRAME_BUFFER_ELEMENTS_DEPTH = FRAME_WIDTH * FRAME_HEIGHT 

DDS_TOPIC_SIM_CAMERA_DEPTH = "rt/sim/depth"
DDS_TOPIC_SIM_CAMERA_RGB = "rt/sim/rgb"