/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/gsmst/temp/ImageData.idl
  Source: ImageData.hpp
  Cyclone DDS: v11.0.1

*****************************************************************/
#ifndef DDSCXX_IMAGEDATA_HPP_AB0B935CF7FBB61D6D463BDF277AEE0A
#define DDSCXX_IMAGEDATA_HPP_AB0B935CF7FBB61D6D463BDF277AEE0A

#include <utility>
#include <ostream>
#include <cstdint>
#include <vector>
#include <string>

namespace sim_msgs
{
class ImageData
{
private:
 uint32_t res_x_ = 0;
 uint32_t res_y_ = 0;
 uint32_t stride_ = 0;
 std::string encoding_;
 std::vector<uint8_t> rgb_data_;
 std::vector<uint8_t> depth_data_;

public:
  ImageData() = default;

  explicit ImageData(
    uint32_t res_x,
    uint32_t res_y,
    uint32_t stride,
    const std::string& encoding,
    const std::vector<uint8_t>& rgb_data,
    const std::vector<uint8_t>& depth_data) :
    res_x_(res_x),
    res_y_(res_y),
    stride_(stride),
    encoding_(encoding),
    rgb_data_(rgb_data),
    depth_data_(depth_data) { }

  uint32_t res_x() const { return this->res_x_; }
  uint32_t& res_x() { return this->res_x_; }
  void res_x(uint32_t _val_) { this->res_x_ = _val_; }
  uint32_t res_y() const { return this->res_y_; }
  uint32_t& res_y() { return this->res_y_; }
  void res_y(uint32_t _val_) { this->res_y_ = _val_; }
  uint32_t stride() const { return this->stride_; }
  uint32_t& stride() { return this->stride_; }
  void stride(uint32_t _val_) { this->stride_ = _val_; }
  const std::string& encoding() const { return this->encoding_; }
  std::string& encoding() { return this->encoding_; }
  void encoding(const std::string& _val_) { this->encoding_ = _val_; }
  void encoding(std::string&& _val_) { this->encoding_ = std::move(_val_); }
  const std::vector<uint8_t>& rgb_data() const { return this->rgb_data_; }
  std::vector<uint8_t>& rgb_data() { return this->rgb_data_; }
  void rgb_data(const std::vector<uint8_t>& _val_) { this->rgb_data_ = _val_; }
  void rgb_data(std::vector<uint8_t>&& _val_) { this->rgb_data_ = std::move(_val_); }
  const std::vector<uint8_t>& depth_data() const { return this->depth_data_; }
  std::vector<uint8_t>& depth_data() { return this->depth_data_; }
  void depth_data(const std::vector<uint8_t>& _val_) { this->depth_data_ = _val_; }
  void depth_data(std::vector<uint8_t>&& _val_) { this->depth_data_ = std::move(_val_); }

  bool operator==(const ImageData& _other) const
  {
    (void) _other;
    return res_x_ == _other.res_x_ &&
      res_y_ == _other.res_y_ &&
      stride_ == _other.stride_ &&
      encoding_ == _other.encoding_ &&
      rgb_data_ == _other.rgb_data_ &&
      depth_data_ == _other.depth_data_;
  }

  bool operator!=(const ImageData& _other) const
  {
    return !(*this == _other);
  }

};

std::ostream& operator<<(std::ostream& os, ::sim_msgs::ImageData const& rhs);

} //namespace sim_msgs

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::sim_msgs::ImageData>::getTypeName()
{
  return "sim_msgs::ImageData";
}

template <> constexpr bool TopicTraits<::sim_msgs::ImageData>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::sim_msgs::ImageData>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPELIB
template<> constexpr unsigned int TopicTraits<::sim_msgs::ImageData>::type_map_blob_sz() { return 434; }
template<> constexpr unsigned int TopicTraits<::sim_msgs::ImageData>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::sim_msgs::ImageData>::type_map_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x94,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x21,  0xf2,  0x2c,  0x51,  0x4d,  0x61,  0xbf, 
 0xfb,  0x95,  0xad,  0x5e,  0xa0,  0x75,  0x88,  0x00,  0x7c,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x6c,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x60,  0xe4,  0x9f,  0xa9,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x6c,  0x7e,  0x1f,  0xa5,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x47,  0x10,  0x13,  0x75,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x84,  0xbe,  0xa1,  0xf0, 
 0x10,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0d, 
 0x05,  0xb3,  0xb8,  0x6e,  0x10,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x0d,  0x8b,  0x23,  0xb6,  0xa5,  0xed,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0x7f,  0x8e,  0x0e,  0x23,  0xee,  0x38,  0x24,  0xc0,  0x0b,  0x20,  0x1b,  0xc5,  0x2d,  0xe5,  0x00, 
 0xd5,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0x73,  0x69,  0x6d,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x49,  0x6d, 
 0x61,  0x67,  0x65,  0x44,  0x61,  0x74,  0x61,  0x00,  0xad,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x72,  0x65,  0x73,  0x5f,  0x78,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0x00,  0x06,  0x00,  0x00,  0x00,  0x72,  0x65,  0x73,  0x5f,  0x79,  0x00,  0x00,  0x00, 
 0x15,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x73,  0x74,  0x72,  0x69,  0x64,  0x65,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x09,  0x00,  0x00,  0x00,  0x65,  0x6e,  0x63,  0x6f, 
 0x64,  0x69,  0x6e,  0x67,  0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0d,  0x09,  0x00,  0x00,  0x00,  0x72,  0x67,  0x62,  0x5f, 
 0x64,  0x61,  0x74,  0x61,  0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0d,  0x0b,  0x00,  0x00,  0x00,  0x64,  0x65,  0x70,  0x74, 
 0x68,  0x5f,  0x64,  0x61,  0x74,  0x61,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x7f,  0x8e,  0x0e,  0x23,  0xee,  0x38,  0x24,  0xc0,  0x0b,  0x20,  0x1b, 
 0xc5,  0x2d,  0xe5,  0xf1,  0x21,  0xf2,  0x2c,  0x51,  0x4d,  0x61,  0xbf,  0xfb,  0x95,  0xad,  0x5e,  0xa0, 
 0x75,  0x88, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::sim_msgs::ImageData>::type_info_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x21,  0xf2,  0x2c,  0x51,  0x4d,  0x61,  0xbf,  0xfb,  0x95,  0xad,  0x5e, 
 0xa0,  0x75,  0x88,  0x00,  0x80,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x7f,  0x8e,  0x0e,  0x23,  0xee,  0x38,  0x24,  0xc0,  0x0b,  0x20,  0x1b, 
 0xc5,  0x2d,  0xe5,  0x00,  0xd9,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPELIB

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::sim_msgs::ImageData>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::sim_msgs::ImageData>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::sim_msgs::ImageData);

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::sim_msgs::ImageData>();

namespace {
  static const volatile propvec &properties___sim_msgs__ImageData = get_type_props<::sim_msgs::ImageData>();
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::sim_msgs::ImageData& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.res_x()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.res_y()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.stride()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.rgb_data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.rgb_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.depth_data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.depth_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::sim_msgs::ImageData& instance, key_mode key) {
  const auto &props = get_type_props<::sim_msgs::ImageData>();
  str.set_mode(cdr_stream::stream_mode::write, key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::sim_msgs::ImageData& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.res_x()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.res_y()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.stride()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.rgb_data().size());
      if (!read(streamer, se_1))
        return false;
      instance.rgb_data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.rgb_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.depth_data().size());
      if (!read(streamer, se_1))
        return false;
      instance.depth_data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.depth_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::sim_msgs::ImageData& instance, key_mode key) {
  const auto &props = get_type_props<::sim_msgs::ImageData>();
  str.set_mode(cdr_stream::stream_mode::read, key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::sim_msgs::ImageData& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.res_x()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.res_y()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.stride()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.rgb_data().size());
      if (!move(streamer, se_1))
        return false;
      
      if (se_1 > 0 &&
          !move(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.depth_data().size());
      if (!move(streamer, se_1))
        return false;
      
      if (se_1 > 0 &&
          !move(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::sim_msgs::ImageData& instance, key_mode key) {
  const auto &props = get_type_props<::sim_msgs::ImageData>();
  str.set_mode(cdr_stream::stream_mode::move, key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::sim_msgs::ImageData& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.res_x()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.res_y()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.stride()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      // coverity[dead_error_line]
      if (se_1 > 0 &&
          !max(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      // coverity[dead_error_line]
      if (se_1 > 0 &&
          !max(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::sim_msgs::ImageData& instance, key_mode key) {
  const auto &props = get_type_props<::sim_msgs::ImageData>();
  str.set_mode(cdr_stream::stream_mode::max, key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_IMAGEDATA_HPP_AB0B935CF7FBB61D6D463BDF277AEE0A
