/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/gsmst/temp/ImageData.idl
  Source: ImageData.cpp
  Cyclone DDS: v11.0.1

*****************************************************************/
#include "ImageData.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace sim_msgs
{
std::ostream& operator<<(std::ostream& os, ::sim_msgs::ImageData const& rhs)
{
  (void) rhs;
  os << "[";
  os << "res_x: " << rhs.res_x();
  os << ", res_y: " << rhs.res_y();
  os << ", stride: " << rhs.stride();
  os << ", encoding: " << rhs.encoding();
  os << ", rgb_data: " << rhs.rgb_data();
  os << ", depth_data: " << rhs.depth_data();
  os << "]";
  return os;
}

} //namespace sim_msgs

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::sim_msgs::ImageData>() {
  static std::mutex mtx;
  static propvec props;
  static std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed))
    return props;
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed))
    return props;
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::res_x
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::res_y
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::stride
  props.push_back(entity_properties_t(1, 3, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::encoding
  props.push_back(entity_properties_t(1, 4, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::rgb_data
  props.push_back(entity_properties_t(1, 5, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::depth_data

  entity_properties_t::finish(props, keylist);
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org
