"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: sim_msgs
  IDL file: ImageData_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import sim_msgs


@dataclass
@annotate.final
@annotate.autoid("sequential")
class ImageData_(idl.IdlStruct, typename="sim_msgs.ImageData_"):
    res_x: types.uint32
    res_y: types.uint32
    stride_rgb: types.uint32
    stride_depth: types.uint32
    encoding: str
    rgb_data: types.sequence[types.uint8]
    depth_data: types.sequence[types.float32]
