/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: ImageData_.idl
  Source: ImageData_.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_IMAGEDATA__HPP
#define DDSCXX_IMAGEDATA__HPP

#include <cstdint>
#include <vector>
#include <string>

namespace sim_msgs
{
class ImageData_
{
private:
 uint32_t res_x_ = 0;
 uint32_t res_y_ = 0;
 uint32_t stride_rgb_ = 0;
 uint32_t stride_depth_ = 0;
 std::string encoding_;
 std::vector<uint8_t> rgb_data_;
 std::vector<float> depth_data_;

public:
  ImageData_() = default;

  explicit ImageData_(
    uint32_t res_x,
    uint32_t res_y,
    uint32_t stride_rgb,
    uint32_t stride_depth,
    const std::string& encoding,
    const std::vector<uint8_t>& rgb_data,
    const std::vector<float>& depth_data) :
    res_x_(res_x),
    res_y_(res_y),
    stride_rgb_(stride_rgb),
    stride_depth_(stride_depth),
    encoding_(encoding),
    rgb_data_(rgb_data),
    depth_data_(depth_data) { }

  uint32_t res_x() const { return this->res_x_; }
  uint32_t& res_x() { return this->res_x_; }
  void res_x(uint32_t _val_) { this->res_x_ = _val_; }
  uint32_t res_y() const { return this->res_y_; }
  uint32_t& res_y() { return this->res_y_; }
  void res_y(uint32_t _val_) { this->res_y_ = _val_; }
  uint32_t stride_rgb() const { return this->stride_rgb_; }
  uint32_t& stride_rgb() { return this->stride_rgb_; }
  void stride_rgb(uint32_t _val_) { this->stride_rgb_ = _val_; }
  uint32_t stride_depth() const { return this->stride_depth_; }
  uint32_t& stride_depth() { return this->stride_depth_; }
  void stride_depth(uint32_t _val_) { this->stride_depth_ = _val_; }
  const std::string& encoding() const { return this->encoding_; }
  std::string& encoding() { return this->encoding_; }
  void encoding(const std::string& _val_) { this->encoding_ = _val_; }
  void encoding(std::string&& _val_) { this->encoding_ = _val_; }
  const std::vector<uint8_t>& rgb_data() const { return this->rgb_data_; }
  std::vector<uint8_t>& rgb_data() { return this->rgb_data_; }
  void rgb_data(const std::vector<uint8_t>& _val_) { this->rgb_data_ = _val_; }
  void rgb_data(std::vector<uint8_t>&& _val_) { this->rgb_data_ = _val_; }
  const std::vector<float>& depth_data() const { return this->depth_data_; }
  std::vector<float>& depth_data() { return this->depth_data_; }
  void depth_data(const std::vector<float>& _val_) { this->depth_data_ = _val_; }
  void depth_data(std::vector<float>&& _val_) { this->depth_data_ = _val_; }

  bool operator==(const ImageData_& _other) const
  {
    (void) _other;
    return res_x_ == _other.res_x_ &&
      res_y_ == _other.res_y_ &&
      stride_rgb_ == _other.stride_rgb_ &&
      stride_depth_ == _other.stride_depth_ &&
      encoding_ == _other.encoding_ &&
      rgb_data_ == _other.rgb_data_ &&
      depth_data_ == _other.depth_data_;
  }

  bool operator!=(const ImageData_& _other) const
  {
    return !(*this == _other);
  }

};

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::sim_msgs::ImageData_>::getTypeName()
{
  return "sim_msgs::ImageData_";
}

template <> constexpr bool TopicTraits<::sim_msgs::ImageData_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::sim_msgs::ImageData_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::sim_msgs::ImageData_>::type_map_blob_sz() { return 490; }
template<> constexpr unsigned int TopicTraits<::sim_msgs::ImageData_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::sim_msgs::ImageData_>::type_map_blob() {
  static const uint8_t blob[] = {
 0xa4,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x7b,  0xbe,  0xaa,  0x71,  0xb6,  0x74,  0x02, 
 0xf1,  0x3e,  0x7f,  0xd2,  0x8d,  0x77,  0x26,  0x00,  0x8c,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x7c,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x60,  0xe4,  0x9f,  0xa9,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x6c,  0x7e,  0x1f,  0xa5,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x78,  0xc3,  0xb5,  0xd0,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x91,  0x2f,  0x74,  0x0b,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x84,  0xbe,  0xa1,  0xf0, 
 0x10,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02, 
 0x05,  0xb3,  0xb8,  0x6e,  0x10,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x09,  0x8b,  0x23,  0xb6,  0xa5,  0x15,  0x01,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0x21,  0x1a,  0x59,  0x07,  0xfc,  0x7a,  0x94,  0x61,  0xd3,  0xce,  0xb9,  0x36,  0x34,  0xcc,  0x00, 
 0xfd,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x15,  0x00,  0x00,  0x00,  0x73,  0x69,  0x6d,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x49,  0x6d, 
 0x61,  0x67,  0x65,  0x44,  0x61,  0x74,  0x61,  0x5f,  0x00,  0x00,  0x00,  0x00,  0xd1,  0x00,  0x00,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x72,  0x65,  0x73,  0x5f,  0x78,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x06,  0x00,  0x00,  0x00,  0x72,  0x65,  0x73,  0x5f, 
 0x79,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x73,  0x74,  0x72,  0x69,  0x64,  0x65,  0x5f,  0x72,  0x67,  0x62,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00, 
 0x0d,  0x00,  0x00,  0x00,  0x73,  0x74,  0x72,  0x69,  0x64,  0x65,  0x5f,  0x64,  0x65,  0x70,  0x74,  0x68, 
 0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00, 
 0x09,  0x00,  0x00,  0x00,  0x65,  0x6e,  0x63,  0x6f,  0x64,  0x69,  0x6e,  0x67,  0x00,  0x00,  0x00,  0x00, 
 0x1b,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02, 
 0x09,  0x00,  0x00,  0x00,  0x72,  0x67,  0x62,  0x5f,  0x64,  0x61,  0x74,  0x61,  0x00,  0x00,  0x00,  0x00, 
 0x1d,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09, 
 0x0b,  0x00,  0x00,  0x00,  0x64,  0x65,  0x70,  0x74,  0x68,  0x5f,  0x64,  0x61,  0x74,  0x61,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x21,  0x1a,  0x59, 
 0x07,  0xfc,  0x7a,  0x94,  0x61,  0xd3,  0xce,  0xb9,  0x36,  0x34,  0xcc,  0xf1,  0x7b,  0xbe,  0xaa,  0x71, 
 0xb6,  0x74,  0x02,  0xf1,  0x3e,  0x7f,  0xd2,  0x8d,  0x77,  0x26, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::sim_msgs::ImageData_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x7b,  0xbe,  0xaa,  0x71,  0xb6,  0x74,  0x02,  0xf1,  0x3e,  0x7f,  0xd2, 
 0x8d,  0x77,  0x26,  0x00,  0x90,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x21,  0x1a,  0x59,  0x07,  0xfc,  0x7a,  0x94,  0x61,  0xd3,  0xce,  0xb9, 
 0x36,  0x34,  0xcc,  0x00,  0x01,  0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::sim_msgs::ImageData_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::sim_msgs::ImageData_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::sim_msgs::ImageData_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::sim_msgs::ImageData_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::sim_msgs::ImageData_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.res_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.res_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.stride_rgb()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.stride_depth()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.rgb_data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.rgb_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.depth_data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.depth_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::sim_msgs::ImageData_& instance, bool as_key) {
  auto &props = get_type_props<::sim_msgs::ImageData_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::sim_msgs::ImageData_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.res_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.res_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.stride_rgb()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.stride_depth()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.rgb_data().size());
      if (!read(streamer, se_1))
        return false;
      instance.rgb_data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.rgb_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.depth_data().size());
      if (!read(streamer, se_1))
        return false;
      instance.depth_data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.depth_data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::sim_msgs::ImageData_& instance, bool as_key) {
  auto &props = get_type_props<::sim_msgs::ImageData_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::sim_msgs::ImageData_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.res_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.res_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.stride_rgb()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.stride_depth()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.rgb_data().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.depth_data().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::sim_msgs::ImageData_& instance, bool as_key) {
  auto &props = get_type_props<::sim_msgs::ImageData_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::sim_msgs::ImageData_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.res_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.res_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.stride_rgb()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.stride_depth()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::sim_msgs::ImageData_& instance, bool as_key) {
  auto &props = get_type_props<::sim_msgs::ImageData_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_IMAGEDATA__HPP
